name: Matrix Job
on: 
  workflow_dispatch:
jobs:
  matrix-job:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v6.2.0
        with:
          node-version: ${{ matrix.node_version }}
